alias tlb="cd ~/repos/papers/tlb-prefetching"
alias papers="cd ~/repos/papers"
alias code="cd ~/repos/code"
alias pics="cd ~/repos/pics"
alias dow="cd ~/Downloads"
alias repos="cd ~/repos"
alias sl="cd ~/shell-files"

alias ref="cd ~/repos/code/ChampSim-ref"
alias rsrc="cd ~/repos/code/ChampSim-ref/src"
alias rinc="cd ~/repos/code/ChampSim-ref/inc"

alias cs="cd ~/repos/code/ChampSim-dev"
alias cm="cd ~/repos/code/ChampSim-dev/cmake_build"
alias rtests="cd ~/repos/code/ChampSim-dev/cmake_build/tests"
alias utests="cd ~/repos/code/ChampSim-dev/test/cpp/src"
alias utestbin="cd ~/repos/code/ChampSim-dev/test/bin/"
alias src="cd ~/repos/code/ChampSim-dev/src"
alias inc="cd ~/repos/code/ChampSim-dev/inc"
alias rs="cd ~/repos/code/ChampSim-dev/results"
alias sc="cd ~/repos/code/ChampSim-dev/scripts"
alias sim="cd ~/repos/code/ChampSim-dev/results/simulation-data"
alias rec="cd ~/repos/code/ChampSim-dev/recent_plts"

