alias tlb="cd ~/repos/papers/tlb-prefetching"
alias papers="cd ~/repos/papers"
alias code="cd ~/repos/code"
alias pics="cd ~/repos/pics"
alias dow="cd ~/Downloads"
alias repos="cd ~/repos"
alias plan="cd ~/repos/research_plan"
alias sll="cd ~/shell-files"

alias ref="cd ~/repos/code/ChampSim-ref"
alias rsrc="cd ~/repos/code/ChampSim-ref/src"
alias rinc="cd ~/repos/code/ChampSim-ref/inc"

alias cs="cd ~/repos/code/ChampSim-dev"
alias cm="cd ~/repos/code/ChampSim-dev/cmake_build"
alias rtests="cd ~/repos/code/ChampSim-dev/cmake_build/tests"
alias utests="cd ~/repos/code/ChampSim-dev/test/cpp/src"
alias utestbin="cd ~/repos/code/ChampSim-dev/test/bin/"

alias src="cd ~/repos/code/ChampSim-dev/src"
alias inc="cd ~/repos/code/ChampSim-dev/inc"

alias incs="cd ~/repos/code/ChampSim-dev/inc/inc"
alias def="cd ~/repos/code/ChampSim-dev/inc/inc/def"
alias misc="cd ~/repos/code/ChampSim-dev/inc/inc/misc"
alias stats="cd ~/repos/code/ChampSim-dev/inc/inc/stats"
alias std="cd ~/repos/code/ChampSim-dev/inc/inc/std"
alias structs="cd ~/repos/code/ChampSim-dev/inc/inc/structs"
alias inlined="cd ~/repos/code/ChampSim-dev/inc/inc/inlined"
alias vars="cd ~/repos/code/ChampSim-dev/inc/inc/vars"

alias rs="cd ~/repos/code/ChampSim-dev/results"
alias sc="cd ~/repos/code/ChampSim-dev/scripts"
alias lan="cd ~/repos/code/ChampSim-dev/scripts/launch"

alias plts="cd ~/repos/code/ChampSim-dev/scripts/pyplots"
alias csv="cd ~/repos/code/ChampSim-dev/scripts/pyplots/csv_data"
alias bhist="cd ~/repos/code/ChampSim-dev/scripts/pyplots/csv_data/bhist"
alias phist="cd ~/repos/code/ChampSim-dev/scripts/pyplots/csv_data/phist"
alias sim="cd ~/repos/code/ChampSim-dev/results/simulation-data"
alias rec="cd ~/repos/code/ChampSim-dev/recent_plts"

alias or="cd ~/repos/code/ChampSim-dev/scripts/oracle_data"
alias bor="cd ~/repos/code/ChampSim-dev/scripts/oracle_data/bhist"
alias por="cd ~/repos/code/ChampSim-dev/scripts/oracle_data/phist"

alias ors="cd ~/repos/code/ChampSim-dev/scripts/oracle_stat"
alias bors="cd ~/repos/code/ChampSim-dev/scripts/oracle_stat/bhist"
alias pors="cd ~/repos/code/ChampSim-dev/scripts/oracle_stat/phist"

