alias dff="git diff"
alias stl="git stash list"
alias stp="git stash pop"
alias sta="git stash"
alias st="git status"
alias sv="git status -v"
alias ct="git commit -m"
alias am="git commit --amend"
alias lg="git log"
alias ph="git push"
alias pl="git pull"
alias br="git branch"
alias au="git add -u"

alias wgit="watch -c 'git log --color=always'"
